### ISSUE TITLE
sgv2 filter doesn't work on https

### ISSUE THREAD

**Issue by zinnerzPT** [GarionCZ/sgv2-filter#5]
SGv2 Filter doesn't work on https SG.
It starts out by not even launching (which is easily fixable), but after manually fixing it myself, it is not filtering the giveaways on the main page.
Thank you very much

Note: I'm using the Tampermonkey Userscript (not sure if there's any other version, just want to make sure)

**Comment by GarionCZ** [comment]
Hi, it should be fixed in the development version already, try it out here https://github.com/GarionCZ/sgv2-filter/raw/master/sgv2-filter.user.js

**Comment by zinnerzPT** [comment]
It's working fine and I don't see any bugs at first glance. Thanks :)
